/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.zidanfathannul.praktikum7.Tugas;

/**
 *
 * @author Sony
 */
public class DaftarMenu extends javax.swing.JFrame {

    /**
     * Creates new form MenuMakanan
     */
    public DaftarMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbetm = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        txtjml1 = new javax.swing.JTextField();
        cbag = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        txtjml7 = new javax.swing.JTextField();
        cbab = new javax.swing.JCheckBox();
        cblg = new javax.swing.JCheckBox();
        cbbg = new javax.swing.JCheckBox();
        cbtmp = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtjml3 = new javax.swing.JTextField();
        txtjml4 = new javax.swing.JTextField();
        txtjml2 = new javax.swing.JTextField();
        cbjp = new javax.swing.JCheckBox();
        cbej = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtjml8 = new javax.swing.JTextField();
        txtjml11 = new javax.swing.JTextField();
        txtjml9 = new javax.swing.JTextField();
        cbnp = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        txtjml5 = new javax.swing.JTextField();
        cbnu = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        txtjml6 = new javax.swing.JTextField();
        cbk = new javax.swing.JCheckBox();
        cbek = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtjml12 = new javax.swing.JTextField();
        txtjml10 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnpesan = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu Makanan :");

        jLabel2.setText("Harga :");

        jLabel3.setText("Jumlah :");

        jLabel4.setText("Menu Minuman :");

        jLabel5.setText("Harga :");

        jLabel6.setText("Jumlah :");

        cbetm.setText("Es Teh Manis");
        cbetm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbetmActionPerformed(evt);
            }
        });

        jLabel7.setText("Rp. 18.000");

        txtjml1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjml1ActionPerformed(evt);
            }
        });

        cbag.setText(" Ayam Goreng");
        cbag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbagActionPerformed(evt);
            }
        });

        jLabel8.setText("Rp. 3.000");

        txtjml7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjml7ActionPerformed(evt);
            }
        });

        cbab.setText(" Ayam Bakar");
        cbab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbabActionPerformed(evt);
            }
        });

        cblg.setText("Lele Goreng");
        cblg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cblgActionPerformed(evt);
            }
        });

        cbbg.setText("Bebek Goreng");
        cbbg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbgActionPerformed(evt);
            }
        });

        cbtmp.setText("Teh Manis Panas");
        cbtmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtmpActionPerformed(evt);
            }
        });

        jLabel9.setText("Rp. 18.500");

        jLabel10.setText("Rp. 15.000");

        jLabel11.setText("Rp. 20.000");

        txtjml3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjml3ActionPerformed(evt);
            }
        });

        txtjml4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjml4ActionPerformed(evt);
            }
        });

        txtjml2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjml2ActionPerformed(evt);
            }
        });

        cbjp.setText("Jeruk Panas");
        cbjp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjpActionPerformed(evt);
            }
        });

        cbej.setText("Es Jeruk");
        cbej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbejActionPerformed(evt);
            }
        });

        jLabel12.setText("Rp. 3.500");

        jLabel13.setText("Rp. 5.000");

        jLabel14.setText("Rp. 4.000");

        txtjml8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjml8ActionPerformed(evt);
            }
        });

        txtjml11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjml11ActionPerformed(evt);
            }
        });

        txtjml9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjml9ActionPerformed(evt);
            }
        });

        cbnp.setText("Nasi Putih");
        cbnp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnpActionPerformed(evt);
            }
        });

        jLabel15.setText("Rp. 5.000");

        txtjml5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjml5ActionPerformed(evt);
            }
        });

        cbnu.setText("Nasi Uduk");
        cbnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnuActionPerformed(evt);
            }
        });

        jLabel16.setText("Rp. 4.000");

        txtjml6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjml6ActionPerformed(evt);
            }
        });

        cbk.setText("Kopi");
        cbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkActionPerformed(evt);
            }
        });

        cbek.setText("Es Kelapa");
        cbek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbekActionPerformed(evt);
            }
        });

        jLabel17.setText("Rp. 9.000");

        jLabel18.setText("Rp. 3.000");

        txtjml12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjml12ActionPerformed(evt);
            }
        });

        txtjml10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjml10ActionPerformed(evt);
            }
        });

        jLabel19.setText("Menu Yang Dipesan :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnpesan.setText("Pesan");
        btnpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesanActionPerformed(evt);
            }
        });

        btncancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbag)
                                .addComponent(cbab)
                                .addComponent(cblg)
                                .addComponent(cbbg))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cbnu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(74, 74, 74)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbnp, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtjml6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtjml5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtjml3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtjml2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtjml1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtjml4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cbetm)
                    .addComponent(cbtmp)
                    .addComponent(cbej)
                    .addComponent(cbjp)
                    .addComponent(cbk)
                    .addComponent(cbek))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtjml12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtjml7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtjml8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtjml9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtjml10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtjml11)))
                        .addGap(127, 127, 127))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnpesan)
                        .addGap(26, 26, 26)
                        .addComponent(btncancel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbag)
                    .addComponent(jLabel7)
                    .addComponent(txtjml1)
                    .addComponent(cbetm)
                    .addComponent(txtjml7)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbab)
                    .addComponent(cbtmp)
                    .addComponent(jLabel9)
                    .addComponent(txtjml2)
                    .addComponent(jLabel8)
                    .addComponent(txtjml8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cblg)
                    .addComponent(jLabel10)
                    .addComponent(txtjml3)
                    .addComponent(cbej)
                    .addComponent(jLabel13)
                    .addComponent(txtjml9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbg)
                    .addComponent(jLabel11)
                    .addComponent(txtjml4)
                    .addComponent(cbjp)
                    .addComponent(jLabel14)
                    .addComponent(txtjml10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbnu)
                    .addComponent(jLabel15)
                    .addComponent(txtjml5)
                    .addComponent(cbk)
                    .addComponent(jLabel18)
                    .addComponent(txtjml11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbnp)
                    .addComponent(jLabel16)
                    .addComponent(txtjml6)
                    .addComponent(cbek)
                    .addComponent(jLabel17)
                    .addComponent(txtjml12))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancel)
                    .addComponent(btnpesan))
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbetmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbetmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbetmActionPerformed

    private void txtjml1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjml1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjml1ActionPerformed

    private void cbagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbagActionPerformed

    private void txtjml7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjml7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjml7ActionPerformed

    private void cbabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbabActionPerformed

    private void cblgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cblgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cblgActionPerformed

    private void cbbgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbgActionPerformed

    private void cbtmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbtmpActionPerformed

    private void txtjml3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjml3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjml3ActionPerformed

    private void txtjml4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjml4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjml4ActionPerformed

    private void txtjml2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjml2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjml2ActionPerformed

    private void cbjpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbjpActionPerformed

    private void cbejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbejActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbejActionPerformed

    private void txtjml8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjml8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjml8ActionPerformed

    private void txtjml11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjml11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjml11ActionPerformed

    private void txtjml9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjml9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjml9ActionPerformed

    private void cbnpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbnpActionPerformed

    private void txtjml5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjml5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjml5ActionPerformed

    private void cbnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbnuActionPerformed

    private void txtjml6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjml6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjml6ActionPerformed

    private void cbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbkActionPerformed

    private void cbekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbekActionPerformed

    private void txtjml12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjml12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjml12ActionPerformed

    private void txtjml10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjml10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjml10ActionPerformed

    private void btnpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesanActionPerformed
        // TODO add your handling code here:
        String tampil;
        tampil ="";
        int bayar = 0;
        if(cbag.isSelected()){
            int jumlah=Integer.parseInt(txtjml1.getText());
            int total;
            total=jumlah*18000;
            bayar=bayar+total;
            tampil+=cbag.getText()+"Rp.18.000"+"x"+jumlah+" = "+total+"\n";
        }if(cbab.isSelected()){
            int jumlah=Integer.parseInt(txtjml2.getText());
            int total;
            total=jumlah*18500;
            bayar=bayar+total;
            tampil+=cbab.getText()+"Rp.18.500"+"x"+jumlah+" = "+total+"\n";
        }if(cblg.isSelected()){
            int jumlah=Integer.parseInt(txtjml3.getText());
            int total;
            total=jumlah*15000;
            bayar=bayar+total;
            tampil+=cblg.getText()+"Rp.15.000"+"x"+jumlah+" = "+total+"\n";
        }if(cbbg.isSelected()){
            int jumlah=Integer.parseInt(txtjml4.getText());
            int total;
            total=jumlah*20000;
            bayar=bayar+total;
            tampil+=cbbg.getText()+"Rp.20.000"+"x"+jumlah+" = "+total+"\n";
        }if(cbnu.isSelected()){
            int jumlah=Integer.parseInt(txtjml5.getText());
            int total;
            total=jumlah*5000;
            bayar=bayar+total;
            tampil+=cbnu.getText()+"Rp.5.000"+"x"+jumlah+" = "+total+"\n";
        }if(cbnp.isSelected()){
            int jumlah=Integer.parseInt(txtjml6.getText());
            int total;
            total=jumlah*4000;
            bayar=bayar+total;
            tampil+=cbnp.getText()+"Rp.4.000"+"x"+jumlah+" = "+total+"\n";
        }if(cbetm.isSelected()){
            int jumlah=Integer.parseInt(txtjml7.getText());
            int total;
            total=jumlah*3500;
            bayar=bayar+total;
            tampil+=cbetm.getText()+"Rp.3.500"+"x"+jumlah+" = "+total+"\n";
        }if(cbtmp.isSelected()){
            int jumlah=Integer.parseInt(txtjml8.getText());
            int total;
            total=jumlah*3000;
            bayar=bayar+total;
            tampil+=cbnp.getText()+"Rp.3.000"+"x"+jumlah+" = "+total+"\n";
        }if(cbej.isSelected()){
            int jumlah=Integer.parseInt(txtjml9.getText());
            int total;
            total=jumlah*5000;
            bayar=bayar+total;
            tampil+=cbej.getText()+"Rp.5.000"+"x"+jumlah+" = "+total+"\n";
        }if(cbjp.isSelected()){
            int jumlah=Integer.parseInt(txtjml10.getText());
            int total;
            total=jumlah*4000;
            bayar=bayar+total;
            tampil+=cbjp.getText()+"Rp.4.000"+"x"+jumlah+" = "+total+"\n";
        }if(cbk.isSelected()){
            int jumlah=Integer.parseInt(txtjml11.getText());
            int total;
            total=jumlah*3000;
            bayar=bayar+total;
            tampil+=cbk.getText()+"Rp.3.000"+"x"+jumlah+" = "+total+"\n";
        }if(cbek.isSelected()){
            int jumlah=Integer.parseInt(txtjml9.getText());
            int total;
            total=jumlah*9000;
            bayar=bayar+total;
            tampil+=cbek.getText()+"Rp.9.000"+"x"+jumlah+" = "+total+"\n";
        }
        btnpesan.setText(tampil+"="+"\n"+"Total bayar="+bayar); 
    }//GEN-LAST:event_btnpesanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnpesan;
    private javax.swing.JCheckBox cbab;
    private javax.swing.JCheckBox cbag;
    private javax.swing.JCheckBox cbbg;
    private javax.swing.JCheckBox cbej;
    private javax.swing.JCheckBox cbek;
    private javax.swing.JCheckBox cbetm;
    private javax.swing.JCheckBox cbjp;
    private javax.swing.JCheckBox cbk;
    private javax.swing.JCheckBox cblg;
    private javax.swing.JCheckBox cbnp;
    private javax.swing.JCheckBox cbnu;
    private javax.swing.JCheckBox cbtmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtjml1;
    private javax.swing.JTextField txtjml10;
    private javax.swing.JTextField txtjml11;
    private javax.swing.JTextField txtjml12;
    private javax.swing.JTextField txtjml2;
    private javax.swing.JTextField txtjml3;
    private javax.swing.JTextField txtjml4;
    private javax.swing.JTextField txtjml5;
    private javax.swing.JTextField txtjml6;
    private javax.swing.JTextField txtjml7;
    private javax.swing.JTextField txtjml8;
    private javax.swing.JTextField txtjml9;
    // End of variables declaration//GEN-END:variables
}
